Next Web Page Project For Microverse
dasileker/responsive-page pull request #1
Opened 2020-08-20 07:56 UTC by dasileker

### In this project we cloned TNW Page 
**Responsive WEB PAGE Project **
_in this project we did the responsive TNW Next Page Clone_ 

- we did a responsive navbar for desktop & tablet & mobile

- a responsive main-body desktop & tablet & mobile

- a responsive footer desktop & tablet & mobile

- we added a linear-gradient colors

2020-08-20 17:55 UTC, SafaErden requested changes
### Status: Require changes ♻️ 🚥

<hr>

Hi **TEAM**, your project is awesome, it really looks exactly like the original.  However, we need a little fix before we can proceed. Kindly find comments below:

<hr>

**_IMPORTANT NOTE_**

- As we discussed on Slack, improper Git/Github Flow is an invalidation reason for the CRRs. In your project, you have an unbalanced and insufficient number of commits. This time you might have a valid reason but please be much more careful about this issue in your upcoming projects. 🥇 

<hr>

- [ ] TNW logo shouldn't be visible for the large screens. Please fix it to be hidden for large screens.

![image](https://user-images.githubusercontent.com/60184961/90803059-d9c13d00-e320-11ea-94e0-3129d2f72f17.png)

- [ ] Let us refactor our CSS file. Let us apply the DRY rule. Make sure that basic CSS bad practices are not used ([article](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png)). 

![image](https://user-images.githubusercontent.com/60184961/90805056-c6fc3780-e323-11ea-87df-a7254a8f1724.png)

<hr>

- [OPTIONAL] You should consider making the section headers bolder to create the same UI with the original page.

![image](https://user-images.githubusercontent.com/60184961/90806008-1d1daa80-e325-11ea-99f8-a49d32ffbcab.png)

<hr>

- As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍 

<hr>


Kindly make these changes and submit another code review 💯 
Happy coding_ 👨‍💻

2020-08-20 17:55 UTC, SafaErden commented on README.md
> +This assignment consists of making [this](https://thenextweb.com/) Clone page of Teardown Designe.
You should be more careful about the typos especially in your README file. It is really important for your repo to have a professional look. (Designe => Design)

2020-08-20 17:55 UTC, SafaErden commented on index.html
> +
- [ ] Please avoid using redundant empty lines between tags and avoid using extra indentation (2 spaces suggested for each indentation). To provide this, I can suggest you to install the proper code-formatter plugins.

2020-08-21 13:28 UTC, dasileker commented on index.html
> +
done

2020-08-21 13:28 UTC, dasileker commented on README.md
> +This assignment consists of making [this](https://thenextweb.com/) Clone page of Teardown Designe.
sorry  and all done thanks

2020-08-21 18:07 UTC, kitpao requested changes
# 👋 Hello @dasileker and @TSHEPO-CLOUD 

You have done an amazing job on your page 🌟 The responsive feature is what most students struggle on in this part, but you managed to do it nice 🏅 

You still have some details to fix, some are small and some are technical, please check them below 🔽 
 
- [ ] When you implemented previous TSE change of hiding the logo in the navbar for big screens, you were left with the space marked in the image (an option to fix it quickly, would be using a padding-right, another option would be using grid-area property, but you can do it as you find it more convenient):
![image](https://user-images.githubusercontent.com/53256139/90920190-78937b00-e3ad-11ea-933b-4e0b779e0292.png)

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-21 18:07 UTC, kitpao commented on main.css
> +}
- [x] You are still repeating the same rules in different parts of your CSS (some examples: `display: grid;`, `width: 100%;`, `height: 100%;`, `color: white;` ). For good coding practices ([check this link](https://speckyboy.com/good-bad-css-practices)), follow the DRY rule (Don't repeat yourself).
![image](https://user-images.githubusercontent.com/53256139/89356769-33203f80-d684-11ea-8a2b-7776e5a73811.png)


  👉 Here you have an explanation of how you can implement it:

  You can use multiple classes for any HTML element, so for example,

  If you use these lines in many classes:
  ```
  color: #fff;
  background-color: #000;
  ```
  and you use it for .class1, .class2, and .class3 
  you can put them inside a single class called for example "common-class" so it will look like this:
  **CSS**
  ```
  .class1 {
    font-size: 24px;
  }
  .class2 {
    font-size: 30px;
  }
  .class3 {
    font-size: 10px;
  }
  .common-class {
    color: #fff;
    background-color: #000
  }
  ```
  and in **HTML**:
  ```
  <nav class="class1 common-class">  <!-- this will have font size of 24px, color of #fff and background-color of #000 -->
  ...
  <div class="class2 common-class">  <!-- this will have font size of 30px, color of #fff and background-color of #000 -->
  ...
  <footer class="class3 common-class">   <!-- this will have font size of 10px, color of #fff and background-color of #000 -->
  ...
  ```

2020-08-21 18:07 UTC, kitpao commented on index.html
> +                <a class="cover-trigger" href="#"></a>
- [x] Extra spaces are still showing, please delete them. You have them through all your index.html

2020-08-22 13:31 UTC, dasileker commented on main.css
> +}
done

2020-08-22 13:31 UTC, dasileker commented on index.html
> +                <a class="cover-trigger" href="#"></a>
done

2020-08-22 15:39 UTC, SafaErden requested changes
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, your project is awesome and it really looks exactly like the original. 👐 However, we need a little fix before we can proceed. Kindly find comments below:

<hr>

- [x] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
* no repeating of the same rule, so please consider following the DRY CSS rules.

<hr>

As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

<hr>

Kindly make the changes and submit another code review
Happy coding_ 👨‍💻 

**Safa ERDEN**

2020-08-22 15:39 UTC, SafaErden commented on style.css
> +  display: flex;
- [x] Your CSS file still has some repeating rules. Please check again the information given by the previous TSE (**kitpao**)  about the DRY rules and apply them to the whole main.css file.

2020-08-22 16:43 UTC, dasileker commented on style.css
> +  display: flex;
sorry I forgot this  line thank you now I corrected all

2020-08-22 17:10 UTC, dasileker commented on style.css
> +  display: flex;
### now the code looks like this
`.sticky-header-right,
.sticky-header-search,
.yellow-bar,
.social-icon-item a,
.cover-article-main,
.cover-main-top,
.cover-articles-small,
.latest-box,
.funding-header,
.funding-container,
.section-container,
.section-pic-box,
.section-2nd-story-box,
.latest-deals-headline,
.social-icons,
.footer-links-list,
.footer-legal,
.footer-legal-text {
  display: flex;
}`

2020-08-22 17:32 UTC, SafaErden requested changes
## Status: Require changes ♻️ 🚥 

Hi **TEAM**, your project is awesome as I mentioned before, but there are some CSS rules that break the DRY CSS rules. I showed some of them below. Please fix **ALL** of the repeating rules(No matter I left a comment or not!)

<hr>

- [x] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
* no repeating of the same rule, so please consider following the DRY CSS rules.

<hr>

Kindly make the changes and submit another code review
Happy coding_ 👨‍💻 

**Safa ERDEN**

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  display: inline;
- This rule repeats 2 times

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  text-decoration: none;
- This rule repeats 3 times

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  font-family: Arial, Helvetica, sans-serif;
- This rule repeats 9 times.

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  width: 100%;
- This rule repeats 5 times.

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  max-width: 100%;
- This rule repeats 6 times.

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  display: none;
- This rule repeats 7 times.

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  font-family: sans-serif;
This rule repeats 2 times.

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  top: 0;
- This rule repeats 2 times.

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  display: flex;
- This rule repeats 4 times.

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  justify-content: space-between;
- Thi rule repeats 6 times

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  align-items: center;
- This rule repeats 7 times.

2020-08-22 17:32 UTC, SafaErden commented on reset.css
> +	display: block;
- This rule repeats 4 times.

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  justify-content: center;
- This rule repeats 6 times.

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +    max-height: 100%;
- This rule repeats 2 times.

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +  flex-direction: column;
- This rule repeats 6 times.

2020-08-22 17:32 UTC, SafaErden commented on style.css
> +}
- Same rules repeating 8 times.

2020-08-24 10:40 UTC, TSHEPO-CLOUD commented on style.css
> +  display: inline;
It's done

2020-08-24 10:40 UTC, TSHEPO-CLOUD commented on style.css
> +  text-decoration: none;
It's done

2020-08-24 10:40 UTC, TSHEPO-CLOUD commented on style.css
> +  width: 100%;
It's done

2020-08-24 10:41 UTC, TSHEPO-CLOUD commented on style.css
> +  max-width: 100%;
It's done

2020-08-24 10:41 UTC, TSHEPO-CLOUD commented on reset.css
> +	display: block;
It's Done

2020-08-24 10:42 UTC, TSHEPO-CLOUD commented on style.css
> +  justify-content: center;
It's Done

2020-08-24 10:44 UTC, TSHEPO-CLOUD commented on style.css
> +    max-height: 100%;
This rules are not repeated, the first one is in the body and the second one is in the media query

2020-08-24 11:15 UTC, TSHEPO-CLOUD commented on style.css
> +  display: none;
It's Done

2020-08-24 11:15 UTC, TSHEPO-CLOUD commented on style.css
> +  font-family: sans-serif;
It's Done

2020-08-24 11:16 UTC, TSHEPO-CLOUD commented on style.css
> +  top: 0;
It's done

2020-08-24 11:16 UTC, TSHEPO-CLOUD commented on style.css
> +  display: flex;
It's Done

2020-08-24 11:16 UTC, TSHEPO-CLOUD commented on style.css
> +  justify-content: space-between;
It's Done

2020-08-24 11:16 UTC, TSHEPO-CLOUD commented on style.css
> +  align-items: center;
Its Done

2020-08-24 11:16 UTC, TSHEPO-CLOUD commented on style.css
> +  flex-direction: column;
It's Done

2020-08-24 11:17 UTC, TSHEPO-CLOUD commented on style.css
> +}
It's Done

2020-08-24 16:00 UTC, expjazz approved these changes
## Status: Project Approved :clap:

Great work implementing the changes required by my colleagues. The page looks awesome, and the code now looks really clean :100: 

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-24 16:13 UTC, merged